<a href="https://colab.research.google.com/github/jeungsengho/python0610/blob/main/1_%EB%84%98%ED%8C%8C%EC%9D%B4_%EB%AA%A8%EB%93%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. **Numpy**

* 수학, 과학 계산용 패키지
* 성능 : 파이썬의 리스트보다 빠름
* 메모리 사이즈 : 파이썬의 리스트보다 적은 메모리를 사용
* 빌트인 함수 : 선형대수, 통계관련 여러 함수들을 내장

In [2]:
# !pip install numpy

In [3]:
import numpy


In [4]:
numpy

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [5]:
# 별칭 (alias) 지정
import numpy as np

In [6]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

### **1-1. array(배열)**
* 여러 값들의 그룹 

In [8]:
arr = np.array([1,2 ,3, 4])

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
type(arr) # numpy.ndarray = n dimension array

numpy.ndarray

In [11]:
list1 = [1, 2, 3, 4]
list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(list1)
print(list2)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [12]:
# 리스트를 ndarray로 생성하는 방법
arr1 = np.array(list1)
arr2 = np.array(list2)

In [15]:
print(arr1)
print(type(arr1))
print(arr2)
print(type(arr2))

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [16]:
arr1.shape  # 차원

(4,)

In [17]:
arr2.shape

(2, 4)

### **1-2.  array의 data 타입**
* ndarray는 list와 다르게 1개의 단일 데이터 타입만 허용

In [18]:
list = [1, 3.14, 'python', '🎃', '1234', True]

In [19]:
list

[1, 3.14, 'python', '🎃', '1234', True]

In [21]:
list[3]

'🎃'

In [22]:
arr = np.array([1, 2, 3, 4])

In [23]:
arr

array([1, 2, 3, 4])

In [24]:
arr = np.array([1, 2, 3, 3.14, 4])

In [25]:
arr

array([1.  , 2.  , 3.  , 3.14, 4.  ])

In [26]:
arr = np.array([1, 2, 3, 3.14, '😜', '1234'])

In [27]:
arr

array(['1', '2', '3', '3.14', '😜', '1234'], dtype='<U32')

In [28]:
# int와 float 타입이 같이 존재하는 경우 int로 설정
arr = np.array([1, 2, 3, 3.14, 4], dtype=int)

In [29]:
arr

array([1, 2, 3, 3, 4])

In [30]:
# int와 str 타입이 같이 존재하는 경우 int로 설정
arr = np.array([1, 2, 3, 3.14, '😜', '1234'], dtype=int)    # 이모티콘 있어서 에러

ValueError: ignored

In [31]:
arr = np.array([1, 2, 3, 3.14, '1234'], dtype=int)      # 숫자 모양을 하고 있는 문자가 있으면 에러 X

In [32]:
arr

array([   1,    2,    3,    3, 1234])

### **1-3. 슬라이싱(Slicing)**
* 배열의 부분 선택

In [40]:
arr = np.array(['😜', '🎃', '😚', '😁', '😎'])
arr.shape

(5,)

In [42]:
print(arr[0])
print(arr[4])
print(arr[-1])

😜
😎
😎


In [45]:
print(arr[0:3])                     # [x:y] -> x부터 y미만까지
print(arr[2:])                      # [x:]  -> x부터 끝까지
print(arr[:2])                      # [:y]  -> 0부터 y미만까지 

['😜' '🎃' '😚']
['😚' '😁' '😎']
['😜' '🎃']


In [62]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [63]:
arr2d.shape

(3, 4)

In [51]:
arr2d[0,2]                      # [x,y]  x행 y열 값


3

In [53]:
arr2d[2,1]                      # 2행 1열 값

10

In [57]:
# 0행을 모두 가져오기
print(arr2d[0])
print(arr2d[0,])
print(arr2d[0,:])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [60]:
# 1열을 모두 가져오기
print(arr2d[:,1])

[ 2  6 10]


In [64]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

### **1-4. Fancy 인덱싱
* 범위가 아닌 특정 index의 집합의 값을 선택하여 추출하고 싶을 때 활용

In [67]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

In [68]:
idx = [1, 3, 5]

In [70]:
arr[idx]

array([23,  7, 65])

In [71]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [72]:
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### **1-5. Boolean 인덱싱
* 조건 필터링을 통하여 Boolean 값을 이용한 색인

In [73]:
arr = np.array(['😜', '🎃', '😚', '😁', '😎'])

In [74]:
myValue = [True, False, True, False, True]

In [75]:
arr[myValue]

array(['😜', '😚', '😎'], dtype='<U1')

In [77]:
myValue = [True, False, True, False]          # 갯수가 틀리면 인덱스 에러
arr[myValue]

IndexError: ignored

In [78]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [79]:
arr2d > 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [80]:
arr2d < 7

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [81]:
arr2d[arr2d>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
arr2d[arr2d<7]

array([1, 2, 3, 4, 5, 6])

# **2. 행렬 연산**

### **2-1. Matrix**
* 행(row)+ 열(column)
* 데이터분석 및 기계학습에서는 행렬을 제외하고 연산할 수 없음



### **2-2. 덧셈 연산**
* shape가 같아야 함
* 같은 position끼리 연산



In [84]:
a = np.array([[1, 2, 3],
             [2, 3, 4]])
b = np.array([[3, 4, 5],
             [1, 2, 3]])

In [85]:
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [87]:
a = np.array([[1, 2, 3],
             [2, 3, 4]])
b = np.array([[4, 5],
             [2, 3]])

In [93]:
a + b   # shape(행열의 갯수)가 달라서 에러

ValueError: ignored

### **2-3. 뺄셈 연산**
* shape가 같아야 함
* 같은 position끼리 연산



In [89]:
a = np.array([[1, 2, 3],
             [2, 3, 4]])
b = np.array([[3, 4, 5],
             [1, 2, 3]])

In [90]:
a - b             # 같은 position(위치) 값 끼리 계산

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [91]:
a = np.array([[1, 2, 3],
             [2, 3, 4]])
b = np.array([[4, 5],
             [2, 3]])

In [96]:
a - b           # shape(행과 열의 갯수)가 달라서 에러

ValueError: ignored

### **2-4. 곱셈 연산**
* shape가 같아야 함
* 같은 position끼리 연산



In [97]:
a = np.array([[1, 2, 3],
             [2, 3, 4]])
b = np.array([[3, 4, 5],
             [1, 2, 3]])

In [98]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

### **2-5. dot product**
* 맞닿는 shape가 같아야 함

In [99]:
a = np.array([[1, 2, 3],
              [1, 2, 3],
              [2, 3, 4]])
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [100]:
a.shape, b.shape

((3, 3), (3, 2))

In [101]:
np.dot(a,b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [102]:
(1*1+2*3+3*5), (1*2+2*4+3*6)
(1*1+2*3+3*5), (1*2+2*4+3*6)
(2*1+3*3+4*5), (2*2+3*4+4*6)

(31, 40)

### **2-6. arange**
*  순차적인 값을 생성할 때 사용

In [104]:
arr = np.arange(1, 11) # 1부터 11미만

In [106]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
arr = np.arange(start=1, stop=11)

In [108]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
arr = np.arange(start=1, stop=11, step=2)

In [110]:
arr

array([1, 3, 5, 7, 9])

In [111]:
arr = range(1, 11)    # 파이썬 표준 함수

In [112]:
arr

range(1, 11)

In [115]:
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [117]:
for i in range(1, 11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [118]:
arr = np.arange(1, 11)
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10


### **2-7. 정렬(sort)**

In [119]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])

In [120]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [121]:
np.sort(arr)    # 기본적으로 오름차순 정렬

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [122]:
np.sort(arr)[::-1]  # 내림차순 정렬

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [123]:
arr # 값이 유지되지 않기 때문에 변수에 저장해야 함

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [124]:
result = np.sort(arr)

In [125]:
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [127]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [135]:
arr2d = np.array([[11, 10, 12, 9],
                 [3, 1, 4, 2],
                 [5, 6, 7, 8]])

In [136]:
arr2d.shape

(3, 4)

In [137]:
# 행 정렬
np.sort(arr2d, axis=0)

array([[ 3,  1,  4,  2],
       [ 5,  6,  7,  8],
       [11, 10, 12,  9]])

In [138]:
# 열 정렬
np.sort(arr2d, axis=1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [139]:
#  마지막 방향
np.sort(arr2d, axis=-1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

### **2-8. 숫자의 단일 연산**

In [140]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[3, 3, 3,],
              [3, 3, 3]])

In [141]:
a + b

array([[4, 5, 6],
       [7, 8, 9]])

In [142]:
a + 3       # 각 position(자리)에 연산

array([[4, 5, 6],
       [7, 8, 9]])

In [144]:
a - 3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [143]:
b + 3

array([[6, 6, 6],
       [6, 6, 6]])