<a href="https://colab.research.google.com/github/jeungsengho/python0610/blob/main/1_%EB%84%98%ED%8C%8C%EC%9D%B4_%EB%AA%A8%EB%93%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Numpy

* 수학, 과학 계산용 패키지
* 성능 : 파이썬의 리스트보다 빠름
* 메모리 사이즈 : 파이썬의 리스트보다 적은 메모리를 사용
* 빌트인 함수 : 선형대수, 통계관련 여러 함수들을 내장

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
import numpy

In [7]:
numpy

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [8]:
# 별칭(alias) 지정
import numpy as np

In [10]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

### **1-1. array(배열)**
* 여러 값들의 그룹

In [11]:
arr = np.array([1, 2, 3, 4])

In [12]:
arr

array([1, 2, 3, 4])

In [14]:
type(arr) # numpy.ndarray = n dimension array -> n차원으로 저장할 수 있는 array다.

numpy.ndarray

In [15]:
list1 = [1, 2, 3, 4]
list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(list1)
print(list2)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [18]:
# 리스트를 ndarray로 생성하는 방법
arr1 = np.array(list1)
arr2 = np.array(list2)

In [21]:
print(arr1)
print(type(arr1))

print(arr2)
print(type(arr2))

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [22]:
arr1.shape

(4,)

In [24]:
arr2.shape

(2, 4)

### **1-2. array의 data 타입**
* ndarray는 list와 다르게 1개의 단일 데이터 타입만 허용

In [25]:
list = [1, 3.14, 'python', '🎃', '1234', True]

In [26]:
list

[1, 3.14, 'python', '🎃', '1234', True]

In [27]:
list[3]

'🎃'

In [28]:
arr = np.array([1, 2, 3, 4])

In [29]:
arr

array([1, 2, 3, 4])

In [31]:
arr = np.array([1, 2, 3, 3.14, 4])

In [32]:
arr

array([1.  , 2.  , 3.  , 3.14, 4.  ])

In [33]:
arr = np.array([1, 2, 3, 3.14, '😜', '1234'])

In [34]:
arr

array(['1', '2', '3', '3.14', '😜', '1234'], dtype='<U32')

In [35]:
# int와 float 타입이 같이 존재하는 경우 int로 설정하는 방법
arr = np.array([1, 2, 3, 3.14, 4], dtype=int)

In [36]:
arr

array([1, 2, 3, 3, 4])

In [37]:
# int와 str 타입이 같이 존재하는 경우 int로 설정하는 방법
arr = np.array([1, 2, 3, 3.14, '😜', '1234'], dtype=int)

ValueError: ignored

In [38]:
arr = np.array([1, 2, 3, 3.14, '1234'], dtype=int) # 숫자모양을 하고 있는 문자가 있을 경우는 에러가 나지 않는다

In [39]:
arr

array([   1,    2,    3,    3, 1234])

### **1-3. 슬라이싱(Slicing)**
* 배열의 부분 선택

In [40]:
arr = np.array(['😜', '🎃', '😂', '😁', '😎'])
arr.shape

(5,)

In [43]:
print(arr[0])
print(arr[4])
print(arr[-1])

😜
😎
😎


In [47]:
print(arr[0:3])
print(arr[2:])
print(arr[:2])
print(arr[::-1])

['😜' '🎃' '😂']
['😂' '😁' '😎']
['😜' '🎃']
['😎' '😁' '😂' '🎃' '😜']


In [48]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [49]:
arr2d.shape

(3, 4)

In [50]:
arr2d[0, 2]

3

In [51]:
arr2d[2, 1]

10

In [56]:
# 0행을 모두 가져오기
print(arr2d[0])
print(arr2d[0,])
print(arr2d[0,:])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [58]:
# 1열을 모두 가져오기
print(arr2d[:,1])

[ 2  6 10]


In [60]:
arr2d[:2, :] # 1행까지 모든 열

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
arr2d[:2, 2:] # 1행까지 2열부터

array([[3, 4],
       [7, 8]])

### **1-4. Fancy 인덱싱**
* 범위가 아닌 특정 index의 집합의 값을 선택하여 추출하고 싶을 때 활용

In [63]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

In [64]:
idx = [1, 3, 5]

In [65]:
arr[idx]

array([23,  7, 65])

In [66]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [67]:
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### **1-5. Boolean 인덱싱**
* 조건 필터링을 통하여 Boolean 값을 이용한 색인

In [69]:
arr = np.array(['😜', '🎃', '😂', '😁', '😎'])

In [70]:
myValue = [True, False, True, False, True]

In [71]:
arr[myValue]

array(['😜', '😂', '😎'], dtype='<U1')

In [72]:
myValue = [True, False, True, False]

In [74]:
arr[myValue]   # 요소의 갯수가 다르면 에러가 난다

IndexError: ignored

In [75]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [76]:
arr2d > 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [77]:
arr2d < 7

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [78]:
arr2d[arr2d>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [79]:
arr2d[arr2d<7]

array([1, 2, 3, 4, 5, 6])

# **2. 행렬 연산**

### **2-1. Matrix**
* 행(row) + 열(column)
* 데이터분석 및 기계학습에서는 행렬을 제외하고 연산할 수 없음

### **2-2. 덧셈 연산**
* shape가 같아야 함
* 같은 position끼리 연산

In [80]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [81]:
a + b     # 각각의 같은 포지션(위치) 끼리 더해진다.

array([[4, 6, 8],
       [3, 5, 7]])

In [82]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[4, 5],
              [2, 3]])

In [85]:
a + b     # shape가 다르면 연산이 되지 않는다.

ValueError: ignored

### **2-3. 뺄셈 연산**
* shape가 같아야 함
* 같은 position끼리 연산

In [86]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [87]:
a - b       # 같은 포지션(위치)끼리 계산된다.

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [88]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[4, 5],
              [2, 3]])

In [90]:
a - b       # shape가 다르면 연산이 되지 않는다.

ValueError: ignored

### **2-4. 곱셈 연산**
* shape가 같아야 함
* 같은 position끼리 연산

In [91]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [92]:
a * b     # 같은 포지션(위치)끼리 계산된다.

array([[ 3,  8, 15],
       [ 2,  6, 12]])

### **2-5. dot product (행열의 곱=내적의 일반화)**
* 맞닿는 shape가 같아야 함
* 앞의 열과 뒤의 행의 갯수가 같아야 함

In [96]:
a = np.array([[1, 2, 3],
              [1, 2, 3],
              [2, 3, 4]])

b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [97]:
a.shape, b.shape

((3, 3), (3, 2))

In [98]:
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [108]:
(1*1 + 2*3 + 3*5), (1*2 + 2*4 + 3*6)
(1*1 + 2*3 + 3*5), (1*2 + 2*4 + 3*6)
(2*1 + 3*3 + 4*5), (2*2 + 3*4 + 4*6)

(31, 40)

### **2-6. arange**
* 순차적인 값을 생성할 때 사용

In [111]:
arr = np.arange(1, 11) # 1부터 11미만

In [112]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
arr = np.arange(start=1, stop=11)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
arr = np.arange(start=1, stop=11, step=2)
arr

array([1, 3, 5, 7, 9])

In [115]:
arr = range(1, 11)  # 파이썬 표준 함수

In [116]:
arr

range(1, 11)

In [117]:
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [118]:
for i in range(1, 11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [119]:
arr = np.arange(1, 11)
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10


### **2-7. 정렬(sort)**

In [123]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])

In [124]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [125]:
np.sort(arr) # 기본적으로 오름차순 정렬

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [126]:
np.sort(arr)[::-1] # 내림차순 정렬

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [128]:
arr # 값이 유지되지 않기 때문에 변수에 저장해야 함

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [129]:
result = np.sort(arr)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [131]:
arr2d = np.array([[11, 10, 12, 9],
                 [3, 1, 4, 2],
                 [5, 6, 7, 8]])

In [132]:
arr2d.shape

(3, 4)

In [133]:
# 행 정렬
np.sort(arr2d, axis=0)

array([[ 3,  1,  4,  2],
       [ 5,  6,  7,  8],
       [11, 10, 12,  9]])

In [134]:
# 열 정렬
np.sort(arr2d, axis=1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [135]:
# 마지막 방향
np.sort(arr2d, axis=-1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

### **2-8. 숫자의 단일 연산**

In [136]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])
b = np.array([[3, 3, 3],
             [3, 3, 3]])

In [137]:
a + b

array([[4, 5, 6],
       [7, 8, 9]])

In [138]:
a + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [139]:
a - 3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [140]:
a * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [141]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])